param_map = {
    "Сайт": "site_domain_name",
    "UTM_source": "utm_source",
    "Расширенная метка UTM_source": "eq_utm_source",
    "UTM_medium": "utm_medium",
    "Расширенная метка UTM_medium": "eq_utm_medium",
    "UTM_campaign": "utm_campaign",
    "Расширенная метка UTM_campaign": "eq_utm_campaign",
    "Источник": "source_new",
    "Канал": "channel_new",
    "Рекламная кампания": "campaign_name",
    "URL страницы обращения": "communication_page_url",
    "Название формы заявки": "form_name",
    "ClientID Яндекс Метрики": "ym_client_id",
    "ClientID Universal Analytics": "ua_client_id",
}
param_list = [
    {"name": "Сайт", "value": "site_domain_name"},
    {"name": "UTM_source", "value": "utm_source"},
    {"name": "Расширенная метка UTM_source", "value": "eq_utm_source"},
    {"name": "UTM_medium", "value": "utm_medium"},
    {"name": "Расширенная метка UTM_medium", "value": "eq_utm_medium"},
    {"name": "UTM_campaign", "value": "utm_campaign"},
    {"name": "Расширенная метка UTM_campaign", "value": "eq_utm_campaign"},
    {"name": "Источник", "value": "source_new"},
    {"name": "Канал", "value": "channel_new"},
    {"name": "Рекламная кампания", "value": "campaign_name"},
    {"name": "URL страницы обращения", "value": "communication_page_url"},
    {"name": "Название формы заявки", "value": "form_name"},
    {"name": "ClientID Яндекс Метрики", "value": "ym_client_id"},
    {"name": "ClientID Universal Analytics", "value": "ua_client_id"},
]